FROM node:alpine
WORKDIR /var/www/covid-corpus/frontend
COPY . .
#
ENV NODE_PATH=./src/
RUN touch .env 
RUN echo "NODE_PATH=./src/" > .env \
    && echo "REACT_APP_BACKEND_API=http://www.covidcorpus.org:8001/api" >> .env \
    && echo "REACT_APP_IMAGES_PATH=http://www.covidcorpus.org:8001/" >> .env
RUN npm install
RUN npm run build
RUN npm install -g serve
CMD ["serve", "-s", "build"]