export const LOGIN_USER_SUCCESS = "CC_USER_LOGIN_SUCCESS";
export const LOGOUT_USER = "CC_USER_LOGOUT";
export const USER_CHANGE_PROFILE_PHOTO = "USER_CHANGE_PROFILE_PHOTO";
export const INFO_ID = " INFO_ID";